"""Update Order models

Revision ID: 16a5ce7747e8
Revises: c38f71e7e8e1
Create Date: 2025-08-29 10:50:10.439294

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16a5ce7747e8'
down_revision: str | Sequence[str] | None = 'c38f71e7e8e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_date')
    # ### end Alembic commands ###
