"""Fix foreign key

Revision ID: 58b02e42bc17
Revises: 416709ce8395
Create Date: 2025-08-27 12:25:02.986909

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b02e42bc17'
down_revision: str | Sequence[str] | None = '416709ce8395'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('menu_item_id', sa.Integer(), nullable=False))
    op.add_column('orderitem', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orderitem', 'menuitems', ['menu_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'quantity')
    op.drop_column('orderitem', 'menu_item_id')
    # ### end Alembic commands ###
