"""Add menuitem relationship

Revision ID: 87627187c8d1
Revises: 58b02e42bc17
Create Date: 2025-08-27 12:32:01.234192

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87627187c8d1'
down_revision: str | Sequence[str] | None = '58b02e42bc17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitem', 'price')
    op.drop_column('orderitem', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orderitem', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
