"""Update Order models

Revision ID: c38f71e7e8e1
Revises: 87627187c8d1
Create Date: 2025-08-28 09:24:23.217089

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c38f71e7e8e1'
down_revision: str | Sequence[str] | None = '87627187c8d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="pending"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
