"""Update Order models

Revision ID: e0da41cabb64
Revises: 16a5ce7747e8
Create Date: 2025-08-30 20:12:02.167309

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0da41cabb64'
down_revision: str | Sequence[str] | None = '16a5ce7747e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'order_id')
    # ### end Alembic commands ###
